[
    {"yon": "pineapple on pizza"},
    {"yon": "birks with socks"},
    {"yon": "dominoes > papa johns"},
    {"yon": "best singer alive = beyonce"},
    {"yon": "White socks"},
    {"yon": "Pizza > Sushi"},
    {"yon": "Deliveroo > Just-Eat"},
    {"yon": "Iphone > Android"},
    {"yon": "Instagram > Tik Tok"},
    {"yon": "Dogs > Cats"},
    {"yon": "USA > Europe"},
    {"yon": "Taylor Swift > Katy Perry"},
    {"yon": "Pussycat Dolls > Spice Girls"},
    {"yon": "Nintendo Switch > PS4"},
    {"yon": "Beach > Mountain"},
    {"yon": "Surf > Ski"},
    {"yon": "Spotify > Apple Music"},
    {"yon": "Crocs"},
    {"yon": "Marmite"},
    {"yon": "Apple Watch"},
    {"yon": "Books > Kindle"},
    {"yon": "Cristiano Ronaldo > Messi"},
    {"yon": "Real Madrid > Barcelona"},
    {"yon": "Pickle on burger"},
    {"yon": "Swimming pool > beach"},
    {"yon": "Pop music > Hip hop"},
    {"yon": "Bill Gates > Steve Jobs"},
    {"yon": "Coca-Cola > Pepsi"},
    {"yon": "Snowboard > Ski"},
    {"yon": "Surf > Bodyboard"},
    {"yon": "Bungee jumping > Skydiving"}
]